### ISSUE TITLE
Push Error

### ISSUE THREAD

**Issue by morrismat** [shenoisam/Software1#19]
error: cannot spawn .git/hooks/pre-push: No such file or directory
error: waitpid for .git/hooks/pre-push failed: No child processes
error: failed to push some refs to 'https://github.com/shenoisam/Software1.git'

**Comment by shenoisam** [comment]
Attempted work around for issue. Need to test on windows machine. Run the following commands and see if it works in git bash. 

# Checkout my branch
``` git checkout Sam ```

# Run the hook install script
```./code/install-hooks-windows.sh```

# Push to test the script 
```git push```
