### ISSUE TITLE
Add issues on GitHub issues

### ISSUE THREAD

**Issue by shenoisam** [shenoisam/Software1#33]
Add 5 new issues over stuff per person.

**Comment by shenoisam** [comment]
Potential issues: 
 - Merge my pull request and check for bugs 
 - List of known bugs to add to issues and/or fix (plz fix though) 
         - Not all buttons are connected to actionlisteners (I think I forgot to add to Alejandros or Katies I dont remember
         - Runners need to extend EHRRunner so that a logout function can be called 
        - Files need to be renamed so that they are standardized (i.e. Runners and generic screens should all have the same format). 
       - Potentially add a Generic Generic screen from which the other generic screens can extend. 
       - Fix the issue with passing users login credentials to the validate function (right now it just returns the address I think) 
       - Add in a class that allows for the top bar to be reused ( home and logout) thats access specific. Probs will have to make a generic that extends for the three types. 
      - Also I liked @AlejandroNavarro1 abstract methods in generic screen. I implemented an interface for the other two, but we might want to scrap that and go to having an abstract method instead. 
  - DRY code (theres a lot of repeated code)

**Comment by jordanehurt98** [comment]
@shenoisam i didn't hear where we needed to add more issues to github, can you add the time? at 23:28 is where i am hearing his comments about our git hub

**Comment by shenoisam** [comment]
He mentions it at the beginning and somewhere in the middle. I can't find the exact time stamp, however. It's a general comment. I think for the most part we are good GitHub wise, but adding a few more issues won't hurt.

**Comment by jordanehurt98** [comment]
@shenoisam can you review the ones that i just posted
are we supposed to make issues for this iteration or for the next?

**Comment by shenoisam** [comment]
@jordanehurt98 Looks good. I closed the issue with combing packages since its works out well if we keep it that way. I think its for this iteration. He said they TAs are going to check.
