### ISSUE TITLE
Sequence diagrams

### ISSUE THREAD

**Issue by shenoisam** [shenoisam/Software1#34]
- Controller
- Indirect service to connect to database
- Need to redo all of them
- Comment which ones you are going to do below to make sure we have covered them all. 
- Review his comments at 20:48 on the iteration2 video

**Comment by jordanehurt98** [comment]
Jordan's Sequence Diagrams Revisions
Exporting data (file sharing)
Referral letter
Provider notes

- pulled these from the last issue on sequence diagrams

**Comment by morrismat** [comment]
Matthew's Sequence Diagram Revisions:
Visit Patient
Order Tests
Patient Lookup
