### ISSUE TITLE
Use Case Review

### ISSUE THREAD

**Issue by shenoisam** [shenoisam/Software1#4]
- Need to ensure that all use cases are dialogs between system and users. (ie. User did this, System did this). 

-  @jordanehurt98  = Exporting Data, Referral Letter, Provider Notes, Login, Billing, Schedule Patient, Signing up for Patient, Initial Visit, Request Info from another doctor. 

- @AlejandroNavarro1  = Visit Patient, View Schedule, Order Tests, Patient Lookup, Exporting Data,Referral Letter, Patient Prescribe, Diagnosis, Provider Notes, Patient Follow up, Population health, View Tests

**Comment by jordanehurt98** [comment]
@AlejandroNavarro1 do you want to keep doing them all in VP or do you wanna do word?

**Comment by AlejandroNavarro1** [comment]
@jordanehurt98 I can't do it in VP because I have the community edition so word will do.

**Comment by shenoisam** [comment]
If you can do it in VP please do for format purposes and send me the generated pdf. Otherwise send me the word version and I'll add it in.

**Comment by AlejandroNavarro1** [comment]
yeah im gonna use the enterprise version then downgrade to the community one.

**Comment by jordanehurt98** [comment]
[JordanUpdatedUseCases.pdf](https://github.com/shenoisam/Software1/files/4189726/JordanUpdatedUseCases.pdf)
