### ISSUE TITLE
Create Combined Frontend Package

### ISSUE THREAD

**Issue by jordanehurt98** [shenoisam/Software1#40]
Need to ensure that we are following our package diagram/proper convention for the packages

currently we have 2-3 packages that are all front end. Need to combine these all into one

**Comment by shenoisam** [comment]
Actually, this is fine. I've updated the domain model to reflect this fact. It allows for a nice separation between views. Theres a provider screen in @AlejandroNavarro1 that I'm not sure why its there, but otherwise, its good.

**Comment by shenoisam** [comment]
<img width="1106" alt="Screen Shot 2020-04-01 at 11 06 00 AM" src="https://user-images.githubusercontent.com/31999037/78160005-f6f47e00-7408-11ea-9bb3-394ba0622c74.png">
