### ISSUE TITLE
Class Constructors from List<Object>

### ISSUE THREAD

**Issue by shenoisam** [shenoisam/Software1#49]
@JohnHarrison2  and @morrismat, 

 When I retrieve documents from database, I get a List<Object> returned. Some of the values of these are NULL and some queries might only return a subset of the fields of the document. Can you create a constructor for each of the classes that can account for this? I can pass in a String [] with the columns names if that helps so the method signature would be something like: 

<classname>(List<Object> data, String[] columnNames)

**Comment by JohnHarrison2** [comment]
Regarding the constructor for the HealthCareProvider class, I don't see any attributes in it. Am I to ignore it until a later date?
