### ISSUE TITLE
John's Sequence Diagrams

### ISSUE THREAD

**Issue by jordanehurt98** [shenoisam/Software1#7]
1. Log in
   - credential verification
   - user panel redirect
   - sign out
2. Schedule patient
3. Initial visit (record info)

**Comment by AlejandroNavarro1** [comment]
@kjwok  review

**Comment by JohnHarrison2** [comment]
[SequenceDiagrams.pdf](https://github.com/shenoisam/Software1/files/4295782/SequenceDiagrams.pdf)
