### ISSUE TITLE
Katie's Sequence Diagrams

### ISSUE THREAD

**Issue by jordanehurt98** [shenoisam/Software1#9]
7. Patient prescribe
8. Diagnosis
9. Billing

**Comment by AlejandroNavarro1** [comment]
@shenoisam  review

**Comment by shenoisam** [comment]
@jordanehurt98 Please review these sequence diagrams

**Comment by kjwok** [comment]
I have the diagrams done, but I'm having some trouble merging my branch so I haven't been able to upload them to gitHub
